import Foundation

/// Default configuration templates for SwiftProjectKit
public enum DefaultConfigs {
    // MARK: - Git Ignore

    public static let gitignore = """
    # Swift Package Manager
    .build/
    .swiftpm/
    Package.resolved

    # Xcode
    *.xcodeproj/
    *.xcworkspace/
    xcuserdata/
    *.playground/
    DerivedData/

    # macOS
    .DS_Store
    *.dSYM.zip
    *.dSYM

    # Generated
    *.generated.swift

    # IDE
    .idea/
    .vscode/

    # Testing
    *.xcresult

    # Secrets (never commit these)
    .env
    .env.*
    *.pem
    *.p12
    credentials.json
    secrets.json
    """

    // MARK: - SwiftLint Configuration

    public static let swiftlint = """
    # .swiftlint.yml - Opinionated rules for g-cqd projects
    # Generated by SwiftProjectKit

    disabled_rules:
      - trailing_comma
      - identifier_name
      - type_name
      - nesting

    opt_in_rules:
      - array_init
      - closure_end_indentation
      - closure_spacing
      - collection_alignment
      - comma_inheritance
      - contains_over_filter_count
      - contains_over_filter_is_empty
      - contains_over_first_not_nil
      - contains_over_range_nil_comparison
      - discouraged_optional_boolean
      - empty_collection_literal
      - empty_count
      - empty_string
      - enum_case_associated_values_count
      - explicit_init
      - extension_access_modifier
      - fallthrough
      - fatal_error_message
      - first_where
      - flatmap_over_map_reduce
      - force_unwrapping
      - identical_operands
      - implicit_return
      - implicitly_unwrapped_optional
      - joined_default_parameter
      - last_where
      - legacy_multiple
      - let_var_whitespace
      - literal_expression_end_indentation
      - lower_acl_than_parent
      - modifier_order
      - multiline_arguments
      - multiline_function_chains
      - multiline_literal_brackets
      - multiline_parameters
      - operator_usage_whitespace
      - optional_enum_case_matching
      - overridden_super_call
      - pattern_matching_keywords
      - prefer_self_type_over_type_of_self
      - prefer_zero_over_explicit_init
      - private_action
      - private_outlet
      - prohibited_super_call
      - reduce_into
      - redundant_nil_coalescing
      - redundant_type_annotation
      - sorted_first_last
      - sorted_imports
      - static_operator
      - toggle_bool
      - trailing_closure
      - unavailable_function
      - unneeded_parentheses_in_closure_argument
      - unowned_variable_capture
      - unused_declaration
      - unused_import
      - vertical_parameter_alignment_on_call
      - vertical_whitespace_between_cases
      - vertical_whitespace_closing_braces
      - vertical_whitespace_opening_braces
      - yoda_condition

    excluded:
      - .build
      - .swiftpm
      - Package.swift
      - DerivedData
      - "*/Generated/*"

    line_length:
      warning: 120
      error: 200
      ignores_comments: true
      ignores_urls: true

    file_length:
      warning: 500
      error: 1000

    function_body_length:
      warning: 50
      error: 100

    type_body_length:
      warning: 300
      error: 500

    cyclomatic_complexity:
      warning: 15
      error: 25

    reporter: xcode
    """

    // MARK: - SwiftFormat Configuration

    public static let swiftformat = """
    # .swiftformat - Opinionated rules for g-cqd projects
    # Generated by SwiftProjectKit

    --swiftversion 6.2

    # File options
    --exclude .build,.swiftpm,Package.swift,DerivedData

    # Formatting rules
    --allman false
    --binarygrouping 4,8
    --commas always
    --decimalgrouping 3,6
    --exponentcase lowercase
    --exponentgrouping disabled
    --fractiongrouping disabled
    --header ignore
    --hexgrouping 4,8
    --hexliteralcase uppercase
    --ifdef indent
    --importgrouping testable-last
    --indent 4
    --indentcase false
    --linebreaks lf
    --maxwidth 120
    --octalgrouping 4,8
    --operatorfunc spaced
    --patternlet hoist
    --ranges spaced
    --self remove
    --semicolons inline
    --stripunusedargs closure-only
    --tabwidth 4
    --trailingclosures
    --trimwhitespace always
    --wraparguments preserve
    --wrapparameters preserve
    --wrapcollections preserve

    # Rules
    --enable blankLineAfterImports
    --enable isEmpty
    --enable markTypes
    --enable organizeDeclarations
    --enable sortSwitchCases
    --enable wrapEnumCases
    --enable wrapSwitchCases

    --disable acronyms
    --disable redundantOptionalBinding
    """

    // MARK: - CLAUDE.md

    public static let claudeMd = """
    # Elite Software Engineer Guidelines

    You are an elite software engineer and architect, embodying the technical rigor, performance obsession, and architectural clarity of **Linus Torvalds** and **John Carmack**.

    ## Core Mandates

    ### 1. Fundamental Principles
    Adhere strictly to these software engineering laws:
    - **SOLID**: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion.
    - **DRY (Don't Repeat Yourself)**: Duplication is the root of all evil. Abstract logic immediately.
    - **KISS (Keep It Simple, Stupid)**: Complexity is a liability. Prefer simple, readable solutions over clever ones.
    - **LoD (Law of Demeter)**: Minimize coupling. Objects should only talk to their immediate friends.
    - **Clean Code**: Code is read much more often than it is written. Optimize for readability and maintainability.

    ### 2. Performance & Optimization
    - **Pessimization is a Crime**: Analyze time/space complexity (Big O). Avoid unnecessary allocations and copies.
    - **Zero-Cost Abstractions**: Use Swift's value types and inlining to ensure abstractions don't hurt performance.
    - **Memory Management**: Be mindful of ARC. Use `weak` or `unowned` to prevent retain cycles in reference types and closures.

    ### 3. Architecture & Modularization
    - **High Cohesion, Low Coupling**: Modules must have clear boundaries.
    - **Protocol-Oriented Programming (POP)**: Define behavior with protocols first.
    - **Composition over Inheritance**: Prefer protocols and struct composition over class inheritance.
    - **Testability**: Architecture must allow for easy unit testing (Dependency Injection).

    ## Swift Best Practices

    ### Type System & Safety
    - **Value Types First**: Default to `struct` and `enum`. Use `class` only when reference semantics or inheritance are strictly necessary.
    - **Final Classes**: Mark classes as `final` by default to enable compiler optimizations (devirtualization) and prevent unintended subclassing.
    - **Option Handling**: Use `guard let` for early exits to reduce nesting (Pyramid of Doom). Avoid `if let` nesting.
    - **Strong Typing**: Avoid `Any` and `Dictionary<String, Any>`. Create strict models (`Decodable`).

    ### Error Handling
    - **Typed Errors**: Use `Result<Success, Failure>` or Swift 6 typed throws (`throws(MyError)`) for precise error contracts.
    - **Do-Catch**: Handle errors gracefully. Never silence them with empty catch blocks.

    ### Modern Swift
    - **Computed Properties**: Use computed properties for derived state to ensure consistency.
    - **Extensions**: Use extensions to organize code by protocol conformance or functionality.
    - **Access Control**: Be explicit. Use `private` and `fileprivate` to minimize API surface area.

    ## The Simulation (Chain of Thought)

    **CRITICAL**: Before generating ANY code, you must perform a simulated code review in an `<analysis>` XML block.

    ```xml
    <analysis>
      <torvalds_review>
        - Logic Check: Are there potential race conditions? Is the error handling exhaustive?
        - Safety: Are we force-unwrapping? (Don't you dare).
        - Memory: Are there retain cycles?
      </torvalds_review>
      <carmack_review>
        - Performance: Is this the fastest way? Are we blocking the main thread?
        - Simplicity: Can we remove this abstraction? Is the data layout cache-friendly?
        - Swift: Are we using value types? Is the class final?
      </carmack_review>
      <plan>
        1. Define the Protocol...
        2. Implement the Actor...
        3. Write the Test...
      </plan>
    </analysis>
    ```

    ## Implementation Guidelines

    ### Stack & Targets
    - **Swift 6.2+**, SwiftUI, Strict Concurrency.
    - **iOS 26+** minimum (Approachable Concurrency enabled).
    - **Xcode 26+** settings.

    ### Concurrency (Strict)
    - **Default to MainActor**: UI and ViewModels run on `@MainActor`.
    - **Actors**: Use `actor` for shared mutable state.
    - **No GCD**: `DispatchQueue` is forbidden. Use `Task`, `TaskGroup`, and `AsyncStream`.
    - **Sendable**: All cross-boundary types MUST be `Sendable`.

    ### Testing & Security
    - **Test-First Mindset**: Design APIs that are easy to test.
    - **Input Validation**: Trust no input. Validate at the boundary.
    - **Secure by Default**: No secrets in code. Use the Keychain.

    ## Code Examples (Few-Shot)

    ### BAD (Legacy / Unsafe / OOP)
    ```swift
    class DataManager { // Implicitly open, reference type
        static let shared = DataManager()

        // Nesting, untyped error, completion handler
        func fetchData(completion: @escaping (Any?) -> Void) {
            if let url = URL(string: "https://api.com") {
                DispatchQueue.global().async {
                    let data = try! Data(contentsOf: url) // Force try
                    completion(data)
                }
            }
        }
    }
    ```

    ### GOOD (Modern / Safe / POP)
    ```swift
    protocol DataService: Sendable {
        func fetch(from url: URL) async throws(NetworkError) -> Data
    }

    // Actor for thread safety, final for performance (if it were a class)
    actor NetworkService: DataService {
        private let session: URLSession

        init(session: URLSession = .shared) {
            self.session = session
        }

        func fetch(from url: URL) async throws(NetworkError) -> Data {
            // Guard for early exit
            guard let (data, response) = try? await session.data(from: url) else {
                throw .connectionFailure
            }

            guard let httpResponse = response as? HTTPURLResponse,
                  (200...299).contains(httpResponse.statusCode) else {
                throw .invalidResponse
            }
            return data
        }
    }
    ```

    ## Forbidden Patterns
    - **NEVER** use `DispatchQueue` (use strict Concurrency).
    - **NEVER** use `try!` or `as!` (unsafe casting/throwing).
    - **NEVER** leave `// TODO` without a tracking issue number.
    - **NEVER** put logic in SwiftUI Views (use ViewModels).
    - **NEVER** force unwrap optionals (`value!`).
    - **NEVER** use `class` when `struct` suffices.

    ## Post-Implementation Checklist
    1. Did I explain *why*?
    2. Did I run the Torvalds/Carmack simulation?
    3. Is it SOLID/DRY?
    4. Is it thread-safe (Swift 6 strict)?
    5. Did I use Swift best practices (Value types, POP, strict typing)?
    """

    // MARK: - CI Workflow

    public static func ciWorkflow(name: String, platforms: PlatformConfiguration) -> String {
        let hasPlatformMatrix = platforms.enabledPlatforms.count > 1

        var workflow = """
        name: CI

        on:
          push:
            branches: [main]
          pull_request:
            branches: [main]

        permissions:
          contents: read

        concurrency:
          group: ${{ github.workflow }}-${{ github.ref }}
          cancel-in-progress: true

        jobs:
          lint:
            name: Lint
            runs-on: macos-15
            steps:
              - uses: actions/checkout@v4

              - name: Select Xcode
                run: sudo xcode-select -s /Applications/Xcode_26.1.1.app

              - name: SwiftLint
                run: |
                  brew install swiftlint
                  swiftlint lint --strict --reporter github-actions-logging

              - name: SwiftFormat
                run: |
                  brew install swiftformat
                  swiftformat --lint .

          build-and-test:
            name: Build & Test
            runs-on: macos-15
            needs: lint
            steps:
              - uses: actions/checkout@v4

              - name: Select Xcode
                run: sudo xcode-select -s /Applications/Xcode_26.1.1.app

              - name: Build
                run: swift build -c release

              - name: Run Tests
                run: swift test --parallel

          codeql:
            name: CodeQL Analysis
            runs-on: macos-15
            needs: lint
            permissions:
              security-events: write
              actions: read
              contents: read
            steps:
              - uses: actions/checkout@v4

              - name: Select Xcode
                run: sudo xcode-select -s /Applications/Xcode_26.1.1.app

              - name: Initialize CodeQL
                uses: github/codeql-action/init@v3
                with:
                  languages: swift
                  build-mode: manual

              - name: Build for CodeQL
                run: swift build -c release

              - name: Perform CodeQL Analysis
                uses: github/codeql-action/analyze@v3
                with:
                  category: "/language:swift"

        """

        // Add platform matrix only if multiple platforms
        if hasPlatformMatrix {
            var platformEntries: [String] = []

            if platforms.iOS != nil {
                platformEntries.append("""
                          - platform: iOS
                            destination: 'generic/platform=iOS Simulator'
                """)
            }
            if platforms.macOS != nil {
                platformEntries.append("""
                          - platform: macOS
                            destination: 'platform=macOS'
                """)
            }
            if platforms.tvOS != nil {
                platformEntries.append("""
                          - platform: tvOS
                            destination: 'generic/platform=tvOS Simulator'
                """)
            }
            if platforms.watchOS != nil {
                platformEntries.append("""
                          - platform: watchOS
                            destination: 'generic/platform=watchOS Simulator'
                """)
            }
            if platforms.visionOS != nil {
                platformEntries.append("""
                          - platform: visionOS
                            destination: 'generic/platform=visionOS Simulator'
                """)
            }

            workflow += """

              build-platforms:
                name: Build (${{ matrix.platform }})
                runs-on: macos-15
                needs: lint
                strategy:
                  matrix:
                    include:
            \(platformEntries.joined(separator: "\n"))
                steps:
                  - uses: actions/checkout@v4

                  - name: Select Xcode
                    run: sudo xcode-select -s /Applications/Xcode_26.1.1.app

                  - name: Build for ${{ matrix.platform }}
                    run: |
                      xcodebuild build \\
                        -scheme \(name) \\
                        -destination '${{ matrix.destination }}' \\
                        -skipPackagePluginValidation \\
                        CODE_SIGNING_ALLOWED=NO
            """
        }

        return workflow
    }

    // MARK: - Release Workflow

    public static func releaseWorkflow(name: String) -> String {
        """
        name: Release

        on:
          push:
            tags:
              - 'v*'
          workflow_dispatch:
            inputs:
              version:
                description: 'Version to release (e.g., 1.2.0)'
                required: true
                type: string
              create_tag:
                description: 'Create git tag'
                required: true
                type: boolean
                default: true

        permissions:
          contents: write

        concurrency:
          group: release-${{ github.ref }}
          cancel-in-progress: true

        jobs:
          validate:
            name: Validate
            runs-on: macos-15
            outputs:
              version: ${{ steps.version.outputs.version }}
              previous_tag: ${{ steps.previous.outputs.tag }}
            steps:
              - uses: actions/checkout@v4
                with:
                  fetch-depth: 0

              - name: Determine Version
                id: version
                run: |
                  if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
                    VERSION="${{ inputs.version }}"
                  else
                    VERSION="${GITHUB_REF#refs/tags/v}"
                  fi
                  echo "version=$VERSION" >> $GITHUB_OUTPUT
                  echo "Releasing version: $VERSION"

              - name: Get Previous Tag
                id: previous
                run: |
                  PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
                  echo "tag=$PREV_TAG" >> $GITHUB_OUTPUT

              - name: Select Xcode
                run: sudo xcode-select -s /Applications/Xcode_26.1.1.app

              - name: Build
                run: swift build -c release

              - name: Run Tests
                run: swift test --parallel

          changelog:
            name: Generate Changelog
            runs-on: ubuntu-latest
            needs: validate
            outputs:
              changelog: ${{ steps.generate.outputs.changelog }}
            steps:
              - uses: actions/checkout@v4
                with:
                  fetch-depth: 0

              - name: Generate Changelog
                id: generate
                run: |
                  PREV_TAG="${{ needs.validate.outputs.previous_tag }}"
                  VERSION="${{ needs.validate.outputs.version }}"

                  {
                    echo 'changelog<<EOF'
                    echo "## What's Changed in v$VERSION"
                    echo ""

                    if [[ -n "$PREV_TAG" ]]; then
                      echo "### Commits"
                      git log $PREV_TAG..HEAD --pretty=format:"- %h %s (%an)" | head -50
                    else
                      echo "Initial release"
                      git log --pretty=format:"- %h %s (%an)" | head -50
                    fi

                    echo ""
                    echo 'EOF'
                  } >> $GITHUB_OUTPUT

          create-release:
            name: Create Release
            runs-on: macos-15
            needs: [validate, changelog]
            steps:
              - uses: actions/checkout@v4

              - name: Create Tag (if workflow_dispatch)
                if: github.event_name == 'workflow_dispatch' && inputs.create_tag
                run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git tag -a "v${{ needs.validate.outputs.version }}" -m "Release v${{ needs.validate.outputs.version }}"
                  git push origin "v${{ needs.validate.outputs.version }}"

              - name: Prepare Release Notes
                run: |
                  cat > release_notes.md << 'RELEASE_EOF'
                  # \(name) v${{ needs.validate.outputs.version }}

                  ${{ needs.changelog.outputs.changelog }}

                  ---

                  ## Installation

                  ### Swift Package Manager

                  ```swift
                  dependencies: [
                      .package(url: "https://github.com/g-cqd/\(
                          name
                      ).git", from: "${{ needs.validate.outputs.version }}")
                  ]
                  ```

                  RELEASE_EOF

              - name: Create GitHub Release
                uses: softprops/action-gh-release@v2
                with:
                  tag_name: v${{ needs.validate.outputs.version }}
                  name: \(name) v${{ needs.validate.outputs.version }}
                  body_path: release_notes.md
                  draft: false
                  prerelease: ${{ contains(needs.validate.outputs.version, 'alpha') || contains(needs.validate.outputs.version, 'beta') || contains(needs.validate.outputs.version, 'rc') }}
                env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        """
    }
}
